### ISSUE TITLE
Upgrade for latest rust-sdl2

### ISSUE THREAD

**Issue by bombless** [xsleonard/rust-sdl2_image#27]
https://github.com/AngryLawyer/rust-sdl2/commit/f92d8302ae207b63d0c19b6f43511ab4667c1a03
Reexports of sdl2-sys are not available now.
I haven't look through the project but it seems that we need to add sdl2-sys as dependency?

**Comment by bombless** [comment]
One more sad news, sdl2::render::Renderer::raw() is gone, so we may need to directly copy some code from sdl2-sys.

**Comment by AngryLawyer** [comment]
Should be good now.
