### ISSUE TITLE
undefined macro 'bitflags!'

### ISSUE THREAD

**Issue by projectilemotion** [xsleonard/rust-sdl2_image#32]
See: https://github.com/AngryLawyer/rust-sdl2/issues/281

```
me@pc:~/rust-sdl2_image$ rustc src/sdl2_image/lib.rs 
src/sdl2_image/lib.rs:44:1: 44:9 error: macro undefined: 'bitflags!'
src/sdl2_image/lib.rs:44 bitflags! {
                         ^~~~~~~~
error: aborting due to previous error
```

Sorry if this bug has been mentioned before; I think it's because I'm on the newest Rust version.

Edit: bug persists after modifying Cargo.toml:
```
[dependencies.sdl2]
sdl2 = "^0"
bitflags = "0.1"
```

**Comment by bombless** [comment]
It seems that here is not active now.
If you just want a compiling project you may like to see my PR here https://github.com/Darkspear7/rust-sdl2_image/pull/1

**Comment by AngryLawyer** [comment]
This should be solved now.
