### ISSUE TITLE
Use rust-sdl2 0.5

### ISSUE THREAD

**Issue by jadpole** [xsleonard/rust-sdl2_image#42]
Hi!

I've upgraded to rust-sdl2 0.5 in my [free-time project/tests sandbox](https://github.com/jadpole/stratos) and changed the version of rust-sdl2 which rust-sdl2_image depends on in a [fork of mine](https://github.com/jadpole/rust-sdl2_image). Turns out it compiles as usual and I haven't had any problem yet. One only needs to change a bit the demo to get it to compile, too, so I included that in my commit.

It is to be noted that I also incremented the version number in Cargo.toml, considering changing dependencies seemed worth it.

I wondered about whether you would like to update the master branch.

**Comment by martinhath** [comment]
I did the exact same thing! This is definitely an issue, and these changes should absolutely be merged in.
@xsleonard ?

**Comment by andelf** [comment]
fixed in #43 .
