### ISSUE TITLE
Bump version and publish to crates.io

### ISSUE THREAD

**Issue by andelf** [xsleonard/rust-sdl2_image#44]
Just pushed:

- Fix compile error under rust-sdl2 0.6.0
- Update dependencies

@AngryLawyer please bump version and publish to crates.io. :)

**Comment by andelf** [comment]
version bumped.
publish this only. :) @AngryLawyer

**Comment by andelf** [comment]
@AngryLawyer

**Comment by AngryLawyer** [comment]
Sorry, been on holiday :)
Done. I've also added you and @xsleonard as maintainers on Cargo so you should be able to publish things while I'm away now :)
