### ISSUE TITLE
No method named `load_texture` found for type `sdl2::render::Renderer<'_>` in the current scope

### ISSUE THREAD

**Issue by Revertron** [xsleonard/rust-sdl2_image#50]
I'm doing exactly like this:

```
let mut sdl_context = sdl2::init().unwrap();
let mut video = sdl_context.video().unwrap();
sdl2_image::init(INIT_PNG | INIT_JPG);
let window  = video.window("Test", 1280, 800).position_centered().opengl().build().unwrap();

let mut renderer = window.renderer().accelerated().build().unwrap();
let mut texture = renderer.load_texture(&Path::new("res/background.png")).unwrap();
```

And compiler gives me this:
src\main.rs:26:29: 26:75 error: no method named `load_texture` found for type `sdl2::render::Renderer<'_>` in the current scope
src\main.rs:26  let mut texture = renderer.load_texture(&Path::new("res/background.png")).unwrap();

**Comment by andelf** [comment]
Have you added  ``use sdl2_image::LoadTexture;`` to your source file?

**Comment by Revertron** [comment]
Yes, I have:
```
use std::path::Path;
use sdl2::event::{Event};
use sdl2::mouse::{Mouse, MouseState};
use sdl2_image::{LoadTexture, INIT_PNG, INIT_JPG};
```

and theese in my Cargo.toml:
```
[dependencies]
rand = "0.3"
sdl2 = "0.9"

[dependencies.sdl2_image]
  git = "https://github.com/xsleonard/rust-sdl2_image"
```

**Comment by andelf** [comment]
your code is ok under my laptop.
plz try: 

- update rust-nightly, or
- cargo update

**Comment by Revertron** [comment]
I've changed dependencies to:
```
[dependencies]
sdl2 = "0.9"
sdl2_image = "0.3"
```
and it worked like a sharm. Something is wrong with cargo and github? Or the version on github isn't working?

**Comment by crumblingstatue** [comment]
This can happen when `sdl2-image` and your crate use different versions of `sdl2`.

**Comment by Impl0x** [comment]
I'm having this exact same problem still. I'm working along a tutorial for using these two libraries and the dependency versions I used based on those instructions cause the error. I even tried setting my dependencies to the versions that Revertron said fixed the issue for him, but that didn't help either. Any word on what I might be able to do to get around this?

**Comment by crumblingstatue** [comment]
@Impl0x 
You need to make sure that `sdl2_image` and your crate use the exact same version of `sdl2`.
Check your `Cargo.lock`, and see if this is the case.

**Comment by Impl0x** [comment]
Ah okay, in my case my `sdl` version was 0.16.0 but `sdl_image` was using 0.15.0. Setting `sdl` to 0.15.0 fixed my problem. Thanks very much!

**Comment by danielpclark** [comment]
Ran into this with SDL2 version 0.18.0 and SDL2_image version 0.16.0.  It works fine if they're both 0.16.0.

Is there a way to patch around this?

**Comment by andelf** [comment]
@danielpclark make a PR to update dependencies of this create. :)

**Comment by andelf** [comment]
@danielpclark fixed
