### ISSUE TITLE
Package version is 1.x, even though API is *not* stable

### ISSUE THREAD

**Issue by crumblingstatue** [xsleonard/rust-sdl2_image#65]
In #60, the version was bumped to `1.0.0`. This was a mistake, as our API is still unstable. At the very least, we depend on an unstable sdl2 crate, so every time we update our sdl2 dependency, it's a breaking change.

This means that we would have to increment the major version (i.e. `2.0.0`, `3.0.0`, ...) after _every_ sdl2 upgrade.

I'm not sure if this can be fixed (either by yanking, or by special request, deleting for good our 1.x versions from crates.io), or if we are stuck having to upgrade the major version every time we make a breaking change.

**Comment by andelf** [comment]
``crates.io`` supports yank. [cargo yank](http://doc.crates.io/crates-io.html#cargo-yank)
``sdl2_mixer``, ``sdl2_ttf`` use same version string as ``sdl2``.
@xsleonard

**Comment by xsleonard** [comment]
@andelf are you able to admin the package on crates.io?

**Comment by andelf** [comment]
@xsleonard yes. 
yanking 1.x will break following repos.  :( 
[serarch result](https://github.com/search?o=desc&q=sdl2_image+language%3ATOML&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93)

**Comment by andelf** [comment]
I'll yank v1.1.0 and v1.0.0.

**Comment by crumblingstatue** [comment]
@andelf Is it actually possible to start releasing lower versions than the ones we already published, even if we yank them? I'm concerned.

**Comment by andelf** [comment]
@crumblingstatue

**Comment by andelf** [comment]
I've published [v0.16.0](https://crates.io/crates/sdl2_image/0.16.0).

but our [crates.io homepage](https://crates.io/crates/sdl2_image) shows:

> This crate has been yanked, but it is still available for download for other crates that may be depending on it.

It only displays newest version of the create. :(

**Comment by andelf** [comment]
refer: https://github.com/rust-lang/crates.io/issues/76

**Comment by andelf** [comment]
:joy: Should we publish a new v1.1.1? Currently our [crates.io page](https://crates.io/crates/sdl2_image) is completely gone.

**Comment by crumblingstatue** [comment]
> Should we publish a new v1.1.1?

That would only make the situation even more confusing. We caused enough mess as it is already.

**Comment by crumblingstatue** [comment]
Closing, since this crate is deprecated.
