### ISSUE TITLE
Move rust-sdl2_image in rust-sdl2

### ISSUE THREAD

**Issue by Cobrand** [xsleonard/rust-sdl2_image#73]
Explained here : AngryLawyer/rust-sdl2#564

This is only a meta issue used to reference the other issue from here

**Comment by andelf** [comment]
@xsleonard

**Comment by xsleonard** [comment]
@andelf I missed the discussion, what do I need to do here?

Is the project moved into the rust-sdl2 repo now?  Should the README be updated to direct people there?

**Comment by Cobrand** [comment]
⁣It has indeed been merged to master, however it is not up yet on crates.io

When the features will be up on crates.io, I will submit a PR that will update the readme (redirecting here) for every module. You will only have to merge this PR and this will be the end of it :)

**Comment by andelf** [comment]
@Cobrand wonderful job!
